project:
  type: website
  output-dir: docs # to publish website on GithubPages

website:
  title: "CPT"
  
  announcement:
    icon: cone-striped
    dismissable: true
    content: "Website under construction"
    type: warning
    position: below-navbar  
  
  navbar:
    left:
      - href: index.qmd
        text: Home
      - 01_codici.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



